### ISSUE TITLE
Feature 1: User can view and reroll random images of dogs

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/peep-dog#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view random images of dogs and their breeds
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see an image of a dog and have the ability to click a button to see another random image of a dog along with their breed
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/127078006-66d8b93c-95d1-409e-bfdc-a2802d901d62.png)
![image](https://user-images.githubusercontent.com/85271794/127078029-7f974cf8-821f-4ed6-b0d0-ccba5a4bf31c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create opening screen
     - [x] Div for app name, paw image, and button
- [x] Add Get Started button to open into the home page
- [x] Create header and footer
- [x] Access public API to retrieve random image of dog and its breed
- [x] Display both in the home page
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
