### ISSUE TITLE
Feature 2: Users can click a button to view more information about the dog's breed

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/peep-dog#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click a button to view more information about the dogs breed
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A button will be provided to show a modal when clicked containing information about the dog breed
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/127104429-6c5af44e-7537-4c2c-b225-99c91329d5ae.png)
![image](https://user-images.githubusercontent.com/85271794/127374738-eea6618a-b582-4a69-98f8-3c3825fbc5c3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an area/link for the user to click on with a prompt for more information
- [x] When clicked, reveal a modal
     - [x] create modal in index.html
     - [x] implement hidden classes
- [x] Modal will contain extra information on the dog
- [x] Create an exit button for the modal to return to the previous page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
