### ISSUE TITLE
Feature 3: User can save pictures

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/peep-dog#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save pictures
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click a button to save the picture into local storage
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/127105018-02be9bb7-f859-469f-b450-139a6bf5c971.png)
![image](https://user-images.githubusercontent.com/85271794/127105042-0d88ac7a-5cac-4b55-8815-01532dfba44b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a button for the user to clicked
- [x] Button will change once clicked
- [x] When clicked, information about the dog will be saved to local storage
- [x] Allow users to click on the button again to unsave the dog
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
