### ISSUE TITLE
Feature 4: Users can view the saved pictures

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/peep-dog#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the saved dogs
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a button to see the saved dogs in a list
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/127105224-ad99c079-487b-4b4f-8b55-32e7a517a2f8.png)
![image](https://user-images.githubusercontent.com/85271794/127105203-0b3517dd-15ac-48be-ba67-5c71413ebfec.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Add button in footer (in mobile) to allow for switching views
- [x] Make buttons function for both returning to random images or seeing saved images
- [x] add function to create and append elements prior to the page being refreshed
- [x] add function to create and append elements after refreshing the page
- [x] make desktop compatible
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
