### ISSUE TITLE
Feature 5: User can add notes/ratings to saved images

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/peep-dog#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add notes/ratings to saved images
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the save button, a modal will appear with a rating and area for comments
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/127105366-c0aa3f6f-f7d4-47b3-a2b7-707fcac58942.png)
![image](https://user-images.githubusercontent.com/85271794/127105390-b8fbb0cb-c2d8-4617-b5a7-f337adf6f081.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create new modal
     - [x] have rating system within modal out of 5
     - [x] make previous "stars" automatically fill out when user clicks on a later one
     - [x] input texarea for comments
     - [x] save button to append information to the data model and to the dom
- [x] modal shows when bookmark button is clicked
- [x] modal hides when save button is clicked 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
