### ISSUE TITLE
Feature 6: User can revise notes/ratings

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/peep-dog#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can revise notes/ratings
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press a button to reopen modal to change rating/comments
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/127105551-86c4218f-9ead-4a35-b754-91620fedad43.png)
![image](https://user-images.githubusercontent.com/85271794/127105523-745a4d49-82ba-4e7d-a5a2-afee7b9a596d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add icon for user to click on in saved views
- [x] when clicked on, reveal the modal for ratings
- [x] prepopulate modal w previous information
- [x] on save, update the information within the data model and dom
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
